#!/bin/zsh

# where we are keeping our dotfiles
dotfiles=$(cd -P -- "$(dirname -- "$0")" && printf "%s\n" "$(pwd -P)")

# these are not dotfiles; don't create symlinks
notdots=(dotlink README.md)

# main

printf "[-] Installing dotfiles from '%s' to '%s'\n" "$dotfiles" "$HOME"

for file in "$dotfiles"/* ; do
    filename=$(basename -- "$file")
    if [[ "${notdots[(r)$filename]}" == "$filename" ]] ; then ;
        # ignore this file
        continue
    fi

    dest="$HOME/.$filename"

    if [[ -h "$dest" ]] ; then ;
        # if it's a symlink, just remove it
        printf "[-] Removing existing '.%s' symlink\n" "$filename"
        rm "$dest"
    elif [[ -f "$dest" ]] ; then ;
        # if it exists, back it up
        backup=$(printf "%s.%s.bak" "$dest" "$(date +%Y%m%dT%H%M%S)")
        printf "[-] Backing up .%s to %s\n" "$filename" "$backup"
        mv "$dest" "$backup"
    fi

    printf "[-] Creating symlink '%s' to '%s'\n" "$dest" "$file"

    ln -s "$file" "$dest"
done

# special steps

if [[ -f "$HOME/.gitmessage" ]] ; then ;
    printf "[-] Using '.gitmessage' as default git commit message\n"
    git config --global commit.template $HOME/.gitmessage
fi

exit 0
